README.md
@haodeqi Could you review this PR? Thanks.
=> Update the link of product document in README.md

integrations/extensions/hubspot/openapi-spec.json, integrations/extensions/hubspot/readme.md, integrations/extensions/hubspot/wa-actions.json
Example used in the blog which describes extensions
DCO 1.1 Signed-off-by: David Amid <davida@il.ibm.com>
=> feat(extensions): add hubspot example

integrations/extensions/starter-kits/metaweather/readme.md
=> chore(readme): Metaweather service down notice

integrations/webchat/examples/README.md, integrations/webchat/examples/share-location/DOCS.md, integrations/webchat/examples/share-location/README.md, integrations/webchat/examples/share-location/actions.json, integrations/webchat/examples/share-location/client/javascript/index.html
This completes the internal IBM issue 53502.
=> feat(Examples): Added an example for sharing the user's location.

integrations/extensions/starter-kits/mailchimp/readme.md
Added some more info that was found to be helpful for implementors
DCO 1.1 Signed-off-by: David Amid <davida@il.ibm.com>
=> chore(docs): mailchimp - how to get campaign id

integrations/extensions/starter-kits/hubspot/advanced/hubspot.advanced.openapi.json, integrations/extensions/starter-kits/hubspot/basic/hubspot.basic.openapi.json, integrations/extensions/starter-kits/hubspot/readme.md
(https://developers.hubspot.com/changelog/upcoming-api-key-sunset)
HubSpot API Key will be sunset in November 30, 2022. Update OpenAPI JSON to bearer and read.me (how to create new access token).
=> fix (hubspot): HubSpot deprecated API Key authorization

integrations/webchat/contributing/template/README.md, integrations/webchat/examples/README.md, integrations/webchat/examples/agents-unavailable/DOCS.md, integrations/webchat/examples/agents-unavailable/README.md, integrations/webchat/examples/agents-unavailable/actions.json, integrations/webchat/examples/agents-unavailable/client/javascript/index.html, integrations/webchat/examples/custom-element/client/javascript-animation/index.html, integrations/webchat/examples/custom-element/client/javascript/index.html, integrations/webchat/examples/custom-response/nbp.openapi.json, integrations/webchat/examples/deep-linking/README.md, integrations/webchat/examples/home-screen-custom-element/README.md, integrations/webchat/examples/page-interaction/DOCS.md, integrations/webchat/examples/page-interaction/client/javascript/index.html, integrations/webchat/examples/pre-post-chat-forms/client/javascript/index.html, integrations/webchat/examples/pre-post-chat-forms/client/react/src/FormContainer.js, integrations/webchat/examples/select-greeting-action/DOCS.md, integrations/webchat/examples/select-greeting-action/client/javascript/index.html, integrations/webchat/examples/set-context/DOCS.md, integrations/webchat/examples/set-context/client/javascript/index.html, integrations/webchat/examples/share-location/README.md, integrations/webchat/examples/speech-and-text/README.md, integrations/webchat/examples/using-carbon/README.md, integrations/webchat/examples/web-chat-security/README.md
- Added an example for how to use handle agents unavailable
- Enhanced the page interaction example
- Modified some examples to use the new is_welcome_request property.
This completes the internal IBM issue 57054 and 57011.
=> feat(Examples): Added more examples and cleaned up some documentation.

integrations/extensions/starter-kits/coveo/coveo.actions.json
This update removes "customer says" phrases from the actions json
=> removing example phrases from actions

integrations/extensions/starter-kits/language-model-complex-informational-tasks/complex-info-palm-actions.json, integrations/extensions/starter-kits/language-model-conversational-search/discovery-palm-actions.json, integrations/extensions/starter-kits/language-model-palm-api/palm2-actions.json, integrations/extensions/starter-kits/language-model-palm-api/palm2-openapi.json
Closes: https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/60973
- Updated openAPI spec, action files in base example, complex info kit & conversational examples
=> LLM starterkit - PaLM add a context param to it's chat model

integrations/extensions/starter-kits/watson-discovery/watson-discovery-query-actions-generic.json, integrations/extensions/starter-kits/watson-discovery/watson-discovery-query-actions-with-examples.json
Closes: https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/60498
=> fix(Discovery starterkit): set passage per document true

integrations/extensions/starter-kits/servicenow/sn.actions.json
Closes: https://github.ibm.com/watson-engagement-advisor/wea-backlog/issues/61989
=> servicenow starterkit incident report issue with status code 200

integrations/extensions/docs/elasticsearch-install-and-setup/how_to_use_web_crawler_in_elasticsearch.md, integrations/extensions/docs/elasticsearch-install-and-setup/watsonx_discovery_install_and_setup.md
This PR adds instructions on how to set up the Elasticsearch web crawler in a CloudPak cluster. It also updates existing instructions to support ELSER v2 model. 
Signed off by: zhongzheng.shu@ibm.com
=> feat: add instructions for web crawler setup on CP4D

integrations/extensions/docs/elasticsearch-install-and-setup/ICD_Elasticsearch_install_and_setup.md
For https://ibm-analytics.slack.com/archives/C05RC9B9TEW/p1705005465339119?thread_ts=1704999933.101979&cid=C05RC9B9TEW
=> chore: update to note comment about ELSER v2

integrations/extensions/starter-kits/testitall/mock-server/.dockerignore, integrations/extensions/starter-kits/testitall/mock-server/.env-sample, integrations/extensions/starter-kits/testitall/mock-server/Dockerfile, integrations/extensions/starter-kits/testitall/mock-server/server/controllers/delay-controller.js, integrations/extensions/starter-kits/testitall/mock-server/server/controllers/oauth-providers/auth-code.js, integrations/extensions/starter-kits/testitall/mock-server/server/controllers/oauth-providers/client-cred.js, integrations/extensions/starter-kits/testitall/mock-server/server/controllers/oauth-providers/custom-apikey.js, integrations/extensions/starter-kits/testitall/mock-server/server/controllers/oauth-providers/password.js, integrations/extensions/starter-kits/testitall/mock-server/server/controllers/security-controller.js, integrations/extensions/starter-kits/testitall/mock-server/server/controllers/test-controller.js, integrations/extensions/starter-kits/testitall/mock-server/server/routes/test-route.js, integrations/extensions/starter-kits/testitall/mock-server/server/server.js, integrations/extensions/starter-kits/testitall/readme.md, integrations/extensions/starter-kits/testitall/testitall.actions.json, integrations/extensions/starter-kits/testitall/testitall.openapi.json
- Update OpenAPI spec to use relative URL
- Remove hosted server info
- Update Mock server to support patch test
- Update `AlmostTooLarge` context test limit to 130KB 
- Renamed `securitySchemes` in OpenAPI spec to v2 standard
=> feat(testitall): Update the testitall starter-kit

integrations/extensions/docs/elasticsearch-install-and-setup/how_to_use_web_crawler_in_elasticsearch.md
Signed off by: zhongzheng.shu@ibm.com
=> fix: add title and url to the chunking script for web crawl

conversational-skills/README.md, conversational-skills/procode-endpoints.md
Adds docs to help explain to a user of Watsonx Assistant how to set up the pro code provider.
DCO 1.1 Signed-off-by: YuQiu Li <YuQiu.Li@ibm.com>
=> chore(docs): Add docs for conversational skills

conversational-skills/procode-endpoints.md
Add confirmation for slot response type
Updated enum list for resolver types
=> Update OpenAPI spec in procode-endpoints.md

conversational-skills/package-lock.json, conversational-skills/procode-skill-sdk-js/Dockerfile, conversational-skills/procode-skill-sdk-js/package-lock.json, conversational-skills/procode-skill-sdk-js/package.json, conversational-skills/procode-skill-sdk-js/src/mock-server/app.js, conversational-skills/procode-skill-sdk-js/src/mock-server/readme.md
DCO 1.1 Signed-off-by: David Amid <davida@il.ibm.com>
=> feat(conversational_skills): add express wrapper

integrations/extensions/docs/elasticsearch-install-and-setup/how_to_configure_advanced_elasticsearch_settings.md
Signed off by: zhongzheng.shu@ibm.com
=> fix: Fix typos for ES filtering guide

integrations/extensions/starter-kits/search-with-custom-service/custom-search-client-setup-guide.md, integrations/extensions/starter-kits/search-with-custom-service/custom-search-server-setup-guide.md, integrations/extensions/starter-kits/search-with-custom-service/examples/examle-milvus-server.py, integrations/extensions/starter-kits/search-with-custom-service/examples/example-simple-server.py, integrations/extensions/starter-kits/search-with-custom-service/examples/example-web-chat-client.html, integrations/extensions/starter-kits/search-with-custom-service/examples/index-with-milvus.py
Setup guides & examples for both Client & Server side search
=> chore(BYOR): Add starter kits for Client & Server Side Search

conversational-skills/README.md
updated auth in examples to use basic auth.
```-u "apikey:{{apikey}}' ```
updated ```-x``` to ```-X```
=> Update pro-code convo skills README.md

conversational-skills/procode-endpoints.md
Expand the types of slot.value.normalized to include number, boolean, object, array along with string
=> Update slot value normalized types

integrations/extensions/starter-kits/testitall/mock-server/server/controllers/webhook-controller.js, integrations/extensions/starter-kits/testitall/mock-server/server/routes/webhook-route.js
add endpoint for pre run and post run webhooks
also add create and list log endpoints
DCO 1.1 Signed-off-by: Anthony Queen <anthony.queen@ibm.com>
=> add webhook routes

conversational-skills/procode-spec.yaml
Also syncs up changes from spec in markdown with spec in procode-spec.yaml
=> Add confirmation to the enum of slot types

integrations/extensions/starter-kits/testitall/mock-server/server/controllers/webhook-controller.js, integrations/extensions/starter-kits/testitall/mock-server/server/server.js
add all auth types for all webhook routes
DCO 1.1 Signed-off-by: Anthony Queen <anthony.queen@ibm.com>
=> feat(webhooks): add auth for webhooks
